# Generated by Django 5.2.9 on 2025-12-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
