# Generated by Django 5.2.9 on 2025-12-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visit_files/')),
                ('file_type', models.CharField(choices=[('xray', 'X-Ray'), ('report', 'Report'), ('prescription', 'Prescription'), ('photo', 'Photo'), ('consent', 'Consent Form'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='visits.visit')),
            ],
        ),
    ]
