# Generated by Django 5.2.9 on 2025-12-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0003_alter_clinic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('medical_alerts', models.TextField(blank=True)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'), models.Index(fields=['name'], name='patients_pa_name_8d04ea_idx')],
                'unique_together': {('clinic', 'patient_id')},
            },
        ),
    ]
